### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by NPJR** [sqd/easier-cc-banner#1]
Hi,

I'm trying to use the new CC Banner, but there are no instructions on how to use it so I'm very confused. I downloaded the Chrome extension, but I'm not sure what to do now. I went to the old banner login, but it's just the same. I'm not very techy, so if you guys could spell it out for me, that would be awesome! 

Thanks!

**Comment by sqd** [comment]
@NPJR Hi! Thank you for using Easier CC Banner! Please get the latest version from Chrome store (just use this [link](http://easierbanner.cc)). Login as usual and click on "Student", and you're good to go! Have a nice day!
